env:
  matrix:
  - packer_version=1.2.1
  
sudo: required
language: bash
before_install:
- wget https://releases.hashicorp.com/packer/packer_${packer_version}/packer_${tf_version}_linux_amd64.zip -O /tmp/packer.zip
- sudo unzip -d /usr/local/bin/ /tmp/packer.zip

script:
- cd ${TRAVIS_BUILD_DIR}/; packer build * || exit 1