language: python
python:
  - "2.7"

env:
  matrix:
  - packer_files=ami

sudo: required
language: bash
before_install:
- openssl aes-256-cbc -K $encrypted_a100f140aa23_key -iv $encrypted_a100f140aa23_iv
  -in chef_secrets.tgz.enc -out chef_secrets.tgz -d
- tar xvzf chef_secrets.tgz

script:
- cd ${TRAVIS_BUILD_DIR}/; python build/packer_build.py --packer-dir=${packer_files}
